### ISSUE TITLE
Why your bot comes inside our pull request?

### ISSUE THREAD

**Issue by ldez** [redhat-developer/devspaces-images#357]
https://github.com/traefik/traefik/pull/9515#issuecomment-1322623732

<details>

![Screenshot 2022-11-21 at 22-34-41 New logger for the Traefik logs by ldez · Pull Request #9515 · traefik_traefik](https://user-images.githubusercontent.com/5674651/203163915-6abe33a7-7ef3-4636-b2a8-a543332dd92f.png)

</details>

Can you stop that? ping @nickboldt

**Comment by nickboldt** [comment]
Bot is commenting on upstream pull requests included in Red Hat OpenShift Dev Spaces, mostly intended for Eclipse Che developers. I can disable it for traefik (which we also use / rebuild / include). 

Sorry about that!

**Comment by ldez** [comment]
Thank you for the quick answer.
Can you disable the bot comments for Traefik?

It's a bit weird to comment on pull requests outside of the RedHat galaxy, maybe you can restrict globally the scope of bot comments.

**Comment by nickboldt** [comment]
yeah, working on a fix in https://github.com/eclipse/che/issues/21795#issuecomment-1322919374 ... I've already reconfigured the PR comment creation logic so that if there's a TAG being used instead of a branch, no comments will be added to PRs. 

Already seems to be working as I kicked off a build 13 mins ago and there are no new comments on https://github.com/traefik/traefik/pull/9515

**Comment by ldez** [comment]
Thank you :+1:
